pub const VAULT_SEED: &[u8] = b"vault";
pub const AUTHORITY_SEED: &[u8] = b"authority";
pub const ADMIN_SEED: &[u8] = b"admin";
pub const TREASURY_SEED: &[u8] = b"treasury";
pub const LOAN_SEED: &[u8] = b"loan";
pub const DEPOSITOR_SEED: &[u8] = b"depositor";
pub const DEPLOYER_SEED: &[u8] = b"deployer";
pub const PROTOCOL_CONFIG_SEED: &[u8] = b"config";
pub const SECONDS_PER_YEAR: u64 = 31_536_000;
pub const SHARE_DECIMALS: u128 = 1_000_000_000; // 1e9 precision